# Generated by Django 4.1.3 on 2022-11-15 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('nome_aluno', models.CharField(max_length=255, verbose_name='Nome do Aluno')),
                ('sobrenome_aluno', models.CharField(max_length=255, verbose_name='Nome do Sobrenome')),
                ('idade_aluno', models.IntegerField(null=True)),
                ('email_responsavel', models.CharField(max_length=100, verbose_name='Email do Responsavel')),
                ('telefone_responsavel', models.CharField(max_length=50, verbose_name='Telefone do Responsavel')),
                ('is_active', models.IntegerField(default=1, verbose_name='Ativo')),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplina', to='turmas.turma', verbose_name=' Id da turma')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
