# Generated by Django 4.1.3 on 2022-11-15 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('nome_instituicao', models.CharField(max_length=255, verbose_name='Nome da Instituição')),
                ('telefone_instituicao', models.CharField(max_length=30, verbose_name='Telefone da Instituição')),
                ('email_instituicao', models.CharField(max_length=50, unique=True, verbose_name='Email da Instituição')),
                ('rua_instituicao', models.CharField(max_length=255, verbose_name='Rua da Instituição')),
                ('cidade_instituicao', models.CharField(max_length=100, verbose_name='Cidade da Instituição')),
                ('pais_instituicao', models.CharField(max_length=100, verbose_name='País da Instituição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('nome_professor', models.CharField(max_length=100, verbose_name='Nome do Professor')),
                ('sobrenome_professor', models.CharField(max_length=255, verbose_name='Sobrenome do Professor')),
                ('email_professor', models.CharField(max_length=100, verbose_name='Email do Professor')),
                ('telefone_professor', models.CharField(max_length=50, verbose_name='Telefone do Professor')),
                ('ativo', models.BooleanField(default=0)),
                ('instituicao', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professores', to='usuarios.instituicao', verbose_name='Id da Instituição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('serie_turma', models.CharField(max_length=20, verbose_name='Série da Turma')),
                ('identificador_turma', models.CharField(max_length=1, verbose_name='Identificador da Turma')),
                ('quantidade_alunos', models.IntegerField(null=True)),
                ('id_professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turma', to='usuarios.professor', verbose_name='Id do professor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('nome_instituicao', models.CharField(max_length=255, verbose_name='Nome da Faculdade')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Inicio da Faculdade')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Fim da Faculdade')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico', to='usuarios.professor', verbose_name='Id do professor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('nome_disciplina', models.CharField(max_length=100, verbose_name='Nome da Disciplina')),
                ('professor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas', to='usuarios.professor', verbose_name='Id da Professor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('nome_diretor', models.CharField(max_length=100, verbose_name='Nome do Diretor')),
                ('sobrenome_diretor', models.CharField(max_length=255, verbose_name='Sobrenome do Diretor')),
                ('email_diretor', models.CharField(max_length=100, verbose_name='Email do Diretor')),
                ('telefone_diretor', models.CharField(max_length=50, verbose_name='Telefone do Diretor')),
                ('id_instituicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diretores', to='usuarios.instituicao', verbose_name='Id da Instituição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('horario_inicio', models.CharField(max_length=20, verbose_name='Horario de Inicio')),
                ('horario_fim', models.CharField(max_length=20, verbose_name='Horario de Fim')),
                ('id_disciplina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas', to='usuarios.disciplina', verbose_name='Id da disciplina')),
                ('id_professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas', to='usuarios.professor', verbose_name='Id do professor')),
                ('id_turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas', to='usuarios.turma', verbose_name=' Id da turma')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('nome_aluno', models.CharField(max_length=255, verbose_name='Nome do Aluno')),
                ('sobrenome_aluno', models.CharField(max_length=255, verbose_name='Nome do Sobrenome')),
                ('idade_aluno', models.IntegerField(null=True)),
                ('email_responsavel', models.CharField(max_length=100, verbose_name='Email do Responsavel')),
                ('telefone_responsavel', models.CharField(max_length=50, verbose_name='Telefone do Responsavel')),
                ('id_turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplina', to='usuarios.turma', verbose_name=' Id da turma')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
