# Generated by Django 4.1.3 on 2022-11-15 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretor',
            name='id_instituicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diretores', to='instituicoes.instituicao', verbose_name='Id da Instituição'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='instituicao',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professores', to='instituicoes.instituicao', verbose_name='Id da Instituição'),
        ),
        migrations.DeleteModel(
            name='Instituicao',
        ),
    ]
