# Generated by Django 4.1.3 on 2022-11-15 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
        ('usuarios', '0002_alter_diretor_id_instituicao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='instituicao',
        ),
        migrations.AlterField(
            model_name='aula',
            name='id_professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas', to='professores.professor', verbose_name='Id do professor'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='professor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas', to='professores.professor', verbose_name='Id da Professor'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='id_professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turma', to='professores.professor', verbose_name='Id do professor'),
        ),
        migrations.DeleteModel(
            name='HistoricoAcademico',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
