# Generated by Django 4.1.3 on 2022-11-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoacademico',
            name='observacoes',
            field=models.TextField(default=None, verbose_name='Observações'),
        ),
    ]
