# Generated by Django 4.1.3 on 2022-11-15 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professores', '0003_alter_professor_instituicao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('serie_turma', models.CharField(max_length=20, verbose_name='Série da Turma')),
                ('identificador_turma', models.CharField(max_length=1, verbose_name='Identificador da Turma')),
                ('quantidade_alunos', models.IntegerField(default=0)),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turma', to='professores.professor', verbose_name='Id do professor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
