# Generated by Django 4.1.3 on 2022-11-15 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('nome_disciplina', models.CharField(max_length=100, verbose_name='Nome da Disciplina')),
                ('professor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas', to='professores.professor', verbose_name='Id da Professor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
